# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1crJm0nOl4f-G1rLOTIJKOEAe_Chu5ZFa
"""

def bit(c,a):
  return [c+i for i in a]

def generate(n):
  if n==0: return []
  if n==1: return ['0','1']
  else: return (bit('0',generate(n-1))+bit('1',generate(n-1)))
generate(3)