# -*- coding: utf-8 -*-
"""NaiveBayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9n-HXsCgYtZf2HtdEAOF9MyXH-Gvj-2
"""

import numpy as np


class NaiveBayes:
    def fit(self, X, y):
        #print(X.shape)#-->(800,10)
        n_samples, n_features = X.shape
        self._classes = np.unique(y) #Find the unique elements of an array.
        #print(self._classes) #--> [0 1]
        n_classes = len(self._classes)

        # calculate mean, var, and prior for each class
        self._mean = np.zeros((n_classes, n_features), dtype=np.float64)# row number is n_classes and column number is n_features
        #print(self._mean)
        self._var = np.zeros((n_classes, n_features), dtype=np.float64)
        self._priors = np.zeros(n_classes, dtype=np.float64)
        #print(self._priors)

        for idx, c in enumerate(self._classes):
            X_c = X[y == c] #if y==c then X_c= x[index of y'th value], here len(X)==len(y)==800
            #print(X_c)
            #print("mean",X_c.mean(axis=0))
            self._mean[idx, :] = X_c.mean(axis=0) #here, self._mean[idx, :]--> idx means _mean location. #axis=0 means column-wise mean.
            #print(self._mean)
            self._var[idx, :] = X_c.var(axis=0)
            #print(X_c.shape) #(403,10) (397,10) X_c.shape[0] means 403,397
            self._priors[idx] = X_c.shape[0] / float(n_samples)
            #print(self._priors)
        #print(X_c)

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        posteriors = []

        # calculate posterior probability for each class
        for idx, c in enumerate(self._classes):
            prior = np.log(self._priors[idx])
            posterior = np.sum(np.log(self._pdf(idx, x)))
            posterior = prior + posterior
            posteriors.append(posterior)

        # return class with highest posterior probability
        #print(posteriors)
        #print(np.argmax(posteriors)) #Returns the indices of the maximum values along an axis. By default, the index is into the flattened array, otherwise along the specified axis.
        #print(self._classes[np.argmax(posteriors)])
        return self._classes[np.argmax(posteriors)]

    def _pdf(self, class_idx, x):
        mean = self._mean[class_idx]
        var = self._var[class_idx]
        numerator = np.exp(-((x - mean) ** 2) / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator


# Testing
if __name__ == "__main__":
    # Imports
    from sklearn.model_selection import train_test_split
    from sklearn import datasets

    def accuracy(y_true, y_pred):
        accuracy = np.sum(y_true == y_pred) / len(y_true)
        return accuracy

    X, y = datasets.make_classification(
        n_samples=1000, n_features=10, n_classes=2, random_state=123
    )
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=123
    )

    #print(X_train)
    nb = NaiveBayes()
    nb.fit(X_train, y_train)
    predictions = nb.predict(X_test)

    print("Naive Bayes classification accuracy", accuracy(y_test, predictions))