# -*- coding: utf-8 -*-
"""BomberFighter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15KdRReayQeBxNyQej2qsjCvv_SFo_0CA
"""

#-----------------------Bomber Fighter----------------------------

import math


b=[[80,0],[90,-2],[99,-5],[108,-9],[116,-15],[125,-18],[133,-23],[141,-29],[151,-28],[160,-25],[169,-21],[179,-28]]

f=[0,50]
vf=float(input())
distance=0
st=12
d=0.00
for i in range(0,st,1):
  d=math.sqrt(pow(b[i][0]-f[0],2)+ pow(b[i][1]-f[1],2))
  print(d)
  if d<=distance:
    print("Attact")
    #print(d)
    break
  else:
    cost=(b[i][0]-f[0])/d
    sint=(b[i][1]-f[1])/d
    f[0]=f[0]+vf*cost
    f[1]=f[1]+vf*sint