# -*- coding: utf-8 -*-
"""Bomber&Fighter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsBcTmRrCQxlpcN-D1SIDN92922_bW4O
"""

import random
import math

#vf=float(input())
vf=20
#xf=float(input())
#yf=float(input())
xf=random.randint(1,1000)
yf=random.randint(1,1000)
xb=random.randint(1,1000)
yb=random.randint(1,1000)

flag=0
time=0


while flag==0:
  dis=math.sqrt((xf-xb)**2+ (yf-yb)**2)

  if dis<=100:
    print("The bomber plane shot down at time ",time)
    flag=1
  elif dis>1000:
    print("The bomber plane escape at time ",time)
    flag=1
  else:
    xf=xf+vf*((xb-xf)/dis)
    yf=yf+vf*((yb-yf)/dis)
    xb=random.randint(1,1000)
    yb=random.randint(1,1000)
    time+=1