# -*- coding: utf-8 -*-
"""CobwebSimulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OqHxTFSoxbLNsKzf30zUaenZCbD-o3Wc
"""

import matplotlib.pyplot as plt
import math
print ("Enter the value of a,b,c,d")


a,b,c,d=map(float,input().split())
p=abs((a-c)/(b+d))
Q=a-(b*p)
S=c+(d*p)

if(math.ceil(Q)==math.ceil(S)):
    print("Equilbrium point:" ,Q, "" ,p)
    print("Quality Q:", Q)
    print("price P:",p)
   
else:
    print("there is not equilibrium point")
x=[0, 2*Q-0]
y=[0, 2*p-0]
x1=[0, 2*Q-0]
y1=[p*2, 2*p-p*2]

plt.plot(x,y,x1,y1, color ="blue", linewidth=2)
plt.scatter(Q,p)


p0=1
s1=c+d*p0
p1=(a-s1)/b
print(s1,p1)
plt.scatter(s1,p1)
prev_point=[s1,p1]
p0=p1
for i in range(10):
  s1=c+d*p0
  p1=(a-s1)/b
  print(s1,p1)
  plt.scatter(s1,p1)
  plt.plot([prev_point[0],s1],[prev_point[1],prev_point[1]])
  plt.plot([s1,s1],[prev_point[1],p1])
  prev_point=[s1,p1]
  p0=p1
#plt.scatter(2,5)
plt.show()