# -*- coding: utf-8 -*-
"""GLCG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGmPtSg8qXN_OuQkT8-bDCMyD0vQVl8G
"""

def GLCG(m1,a1,seed1,seed2,R):
    Y1=seed1
    Y2=seed2
    n=100
    X = (Y1 + Y2)%m1 
    preX=X
    cycle=1
    while True:
      R.append(float(X/m1))
      Y1=Y2
      Y2=X
      X = (Y1 + Y2)%m1
      if X!=preX:
        cycle+=1
      else : break
    print("Cycle length: ",cycle)
    #print(R)

m1=5011
a1 = 4001
a2 = 4069
R=list()
seed1=m1-100
seed2=m1-50
GLCG(m1,a1,seed1,seed2,R)
print(R[0:301])