# -*- coding: utf-8 -*-
"""LabBomberFighter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Gz8ydta5w8iVMfqJLoKL5MOAl1XQsD1
"""

import math
b=[[80,0],[90,-2],[99,-5],[108,-9],[116,-15],[125,-18],[133,-23],[141,-29],[151,-28],[160,-25],[169,-21],[179,-28],[180,-17]]

f=[0,50]
vf=20
distance=12
st=12
d=0
flag=0
for i in range(0,st+1,1):
  d=math.sqrt(pow(b[i][0]-f[0],2)+ pow(b[i][1]-f[1],2))
  #print(d)
  if d<=distance:
    print("Attact")
    flag=1
    print(i+1)
    break
  else:
    cost=(b[i][0]-f[0])/d
    sint=(b[i][1]-f[1])/d
    f[0]=f[0]+vf*cost
    f[1]=f[1]+vf*sint
if flag==0:
  print("bomber out of range")