# -*- coding: utf-8 -*-
"""LabFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p5qOb_-HDxk446TMeCfVVLzkPwSyIRer
"""

import math

def GLCG(m1,seed1,seed2,R):
    Y1=seed1
    Y2=seed2
    X = (Y1 + Y2)%m1 
    preX=X
    cycle=1
    while True:
      R.append(float(X/m1))
      Y1=Y2
      Y2=X
      X = (Y1 + Y2)%m1
      if X!=preX:
        cycle+=1
      else : break
    print("Cycle length: ",cycle)

def Kolmogorov_Smirnov(R,n):
    R=sorted(R)
    d_plus = 0
    d_minus = 0
    i = 1
    for value in R:
        d_plus_i = ( (i/n) - value )
        d_minus_i=(value-((i-1)/n))
        if d_plus_i > d_plus:
            d_plus = d_plus_i
        if d_minus_i > d_minus:
            d_minus = d_minus_i
        i += 1
    return max(d_plus, d_minus)


m1=5011
R=list()
seed1=m1-100
seed2=m1-50
GLCG(m1,seed1,seed2,R)
print(R[0:300])


d=Kolmogorov_Smirnov(R[:301],300)

print("Uniform test: ")
print("Kolmogorov_Smirnov: ")
print("D value is: ",d)