# -*- coding: utf-8 -*-
"""Monte Carlo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRaSkWjP9gOq5CGR7cjm2U3sm0D9Lq74
"""

import random
import math
import numpy as np
import matplotlib.pyplot as plt


def f(x,a,b,c):
  return 3*x
#n,a,b,h=200,0,60,150
n,a,b,h=map(int, input("Enter the value of n,a,b,h: ").split())
count=0
xaxis=list()
yaxis=list()
dic=dict()
for i in range(a,b+1):
  dic[i]=0
for i in range(n):
  x=random.randint(a,b)
  y=random.randint(0,h)
  y_cal=f(x,a,b,h)
  if y<=y_cal:
    dic[x]+=1
    count+=1
    xaxis.append(x)
    yaxis.append(y)
    plt.scatter(xaxis,yaxis)
plt.plot([a,a],[0,h])
plt.plot([b,b],[0,h])
plt.plot([a,b],[h,h])
plt.plot([a-2,b+4],[3*(a-2),3*(b+4)])


plt.show()
print("Points in Curve: ",count)
for i in dic:
  print("Division",i,":",dic[i])