# -*- coding: utf-8 -*-
"""Simple Market Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rON85DEqKRsHurTgH0V2LUjtec8DLO09
"""

#there is equilibrium point: 600 3000 -100 2000

import matplotlib.pyplot as plt
import math
print ("Enter the value of a,b,c,d")


a,b,c,d=map(int,input().split())
p=abs((a-c)/(b+d))
Q=a-(b*p)
S=c+(d*p)

if(math.ceil(Q)==math.ceil(S)):
    print("Equilbrium point:" ,Q, "" ,p)
    print("Quality Q:", Q)
    print("price P:",p)
   
else:
    print("there is equilibrium  not point")
   
x=[0, 2*Q-0]
y=[0, 2*p-0]
x1=[0, 2*Q-0]
y1=[0.5, 2*p-0.5]

plt.plot(x,y,x1,y1, color ="blue", linewidth=2)
plt.show()